### ISSUE TITLE
添加账号失败，确定账号密码无误

### ISSUE THREAD

**Issue by SourceOnce** [Yanyutin753/fakeApiTool-One-API#1]
![图片](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/51945211/554ba1c3-6682-4568-b36c-87c7ff640cf7)

**Comment by SourceOnce** [comment]
已解决

**Comment by Yanyutin753** [comment]
有时候拿token可能会报错的，等一会重新登录，重试一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SourceOne ***@***.***&gt;
发送时间: 2023年11月16日 09:45
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] 添加账号失败，确定账号密码无误 (Issue #1)





 
已解决
