### ISSUE TITLE
token更新后 导致我在OneAPI 渠道 手动添加的模型消失了

### ISSUE THREAD

**Issue by Jesn** [Yanyutin753/fakeApiTool-One-API#13]
在fakeApiTool  点击编辑后，token更新后 导致我在OneAPI 渠道 手动添加的模型消失了

之前调用FastGPT 需要手动添加 `text-embedding-ada-002` 和 `gpt-3.5-turbo-1106`, 希望在更新token的时候，还能继续保留之前的配置信息

<img width="1335" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/5728274/30c757ab-b656-4ce6-9c04-942c2fecca70">

**Comment by Yanyutin753** [comment]
现在更新用不了，可能起飞修改一下这个bug





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Darren ***@***.***&gt;
发送时间: 2023年11月24日 23:55
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] token更新后 导致我在OneAPI 渠道 手动添加的模型消失了 (Issue #13)





 
在fakeApiTool  点击编辑后，token更新后 导致我在OneAPI 渠道 手动添加的模型消失了
 
之前调用FastGPT 需要手动添加 text-embedding-ada-002 和 gpt-3.5-turbo-1106, 希望在更新token的时候，还能继续保留之前的配置信息

**Comment by Yanyutin753** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Darren ***@***.***&gt;
发送时间: 2023年11月24日 23:55
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] token更新后 导致我在OneAPI 渠道 手动添加的模型消失了 (Issue #13)





 
在fakeApiTool  点击编辑后，token更新后 导致我在OneAPI 渠道 手动添加的模型消失了
 
之前调用FastGPT 需要手动添加 text-embedding-ada-002 和 gpt-3.5-turbo-1106, 希望在更新token的时候，还能继续保留之前的配置信息

**Comment by Yanyutin753** [comment]
我到时候多加几个模型，这个模型不影响

**Comment by Yanyutin753** [comment]
已更新

**Comment by Jesn** [comment]
> 已更新

真厉害，我以为我睡的晚，没想到还有比我更晚的，开源不易，谢谢大佬
