### ISSUE TITLE
ai-20231127.fakeopen.com 请求报错，早上上班的时候还可以用

### ISSUE THREAD

**Issue by Jesn** [Yanyutin753/fakeApiTool-One-API#16]
one-api  日志
```
 (channel #25): Post "https://ai-20231127.fakeopen.com//v1/chat/completions": unexpected EOF (request id: 202311291031103942667974oiINA0G)
 ```

**Comment by Jesn** [comment]
<img width="899" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/5728274/a2986112-d4d8-438e-aa80-60deb994fac0">
token 过期了，处理下就好了

<img width="723" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/5728274/8a15c3a1-6151-4a21-b977-11c15e1797ce">

这里是否可以配置 Refresh Token ？

**Comment by Jesn** [comment]
下午又不能访问了
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/5728274/00b7134a-1519-4f32-b00b-db2129be5f10)

**Comment by Yanyutin753** [comment]
是不是过期了 session

**Comment by Jesn** [comment]
```
 relay error (channel #48): Post "https://ai-20231129.fakeopen.com//v1/chat/completions": http2: Transport: cannot retry err [stream error: stream ID 1; PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error (request id: 202311291935221067617009k6Rxd8)
 ```

```
[GIN] 2023/11/29 - 19:36:40 | 20231129193608668174786ysgBxmGF | 500 |  31.53876957s |     192.168.2.1 |    POST /v1/chat/completions
[ERR] 2023/11/29 - 19:36:40 | 20231129193608668174786ysgBxmGF | relay error (channel #51): Post "https://ai.fakeopen.com/v1/chat/completions": unexpected EOF (request id: 20231129193608668174786ysgBxmGF)
```
one-api  点下测试，然后再去访问就行了
<img width="1022" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/5728274/c02396e6-8dd6-478d-85eb-afcb028e0782">

**Comment by Jesn** [comment]
测试了 应该和我代理有关，我吧one-api 迁移到了境外就好了

**Comment by Yanyutin753** [comment]
后面试试我的PandoraNext-tokensTool

**Comment by Yanyutin753** [comment]
fakeopen关了的话
就用pandoraNext开个proxy模式
调用自己的
