### ISSUE TITLE
docker 镜像

### ISSUE THREAD

**Issue by lly-ke** [Yanyutin753/fakeApiTool-One-API#2]
docker 你好能提供一下镜像吗

**Comment by Yanyutin753** [comment]
docket我还没试过，安装java和python也能跑这个项目了，我去研究一下docket在写



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 今天你写bug了吗 ***@***.***&gt;
发送时间: 2023年11月16日 13:47
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] docker 镜像 (Issue #2)





 
docker 你好能提供一下镜像吗

**Comment by ceozero** [comment]
+1 等个docker镜像。

**Comment by Yanyutin753** [comment]
你们的镜像是带dockerFile的吗，我的启动命令会随着用户更改，我打包上去，你们得改，这可咋整，我不是很会docker

**Comment by Yanyutin753** [comment]
我问gpt好像懂了，去试试，应该能行

**Comment by ceozero** [comment]
要改的东西做成环境变量呗。

ENV SERVER_PORT=8008
ENV SPRING_DATASOURCE_USERNAME=oneapi
ENV SPRING_DATASOURCE_PASSWORD=your_oneapi_database_password
ENV BASE_URL_WITHOUT_PATH=http://your_website_ip_and_port

CMD ["java", "-jar", "fakeApiTool-0.0.1-SNAPSHOT.jar"]

**Comment by Yanyutin753** [comment]
搞定了，我自己本地跑了，我在把镜像推到dockerhub上面
注册个账号先，确实方便

**Comment by ceozero** [comment]
> 搞定了，我自己本地跑了，我在把镜像推到dockerhub上面 注册个账号先，确实方便

还是建议把数据库地址的变量加上。不然还不是得自己mvn一下。。。

我是直接偷懒把jar挂到容器里用启动命令跑的。

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/132346501/105ff6cd-9c80-4c66-abf9-5a2e975a2653)
是这个吗

**Comment by ceozero** [comment]
> ![image](https://user-images.githubusercontent.com/132346501/284002161-105ff6cd-9c80-4c66-abf9-5a2e975a2653.png) 是这个吗

是的 localhost:3306  你挂docker里除非用host网络，不然也会连不上数据库的。所以还是要改下地址。

**Comment by Yanyutin753** [comment]
docker push yangclivia/fakeapitool:latest
docker run -d --restart=always --name fakeApiTool --net=host yangclivia/fakeapitool:latest --server.port=8008 --spring.datasource.password=你的（oneapi密码） --spring.datasource.username=你的数据库表名（oneapi）--spring.datasource.url=jdbc:mysql://localhost:3306/oneapi（自己填，如果不是localhost，则删除前面的--net=host）--baseUrlWithoutPath=http(https)://你的one-api的id+端口号

**Comment by Yanyutin753** [comment]
试试这个行不行，我等等在优化语句，我去改另一个项目

**Comment by ceozero** [comment]
> 试试这个行不行，我等等在优化语句，我去改另一个项目

传个arm架构的？  没有amd环境来测试。

**Comment by Yanyutin753** [comment]
docker pull yangclivia/fakeapitool:latest
docker run -d --restart=always --name fakeApiTool --net=host yangclivia/fakeapitool:latest --server.port=8008 --spring.datasource.password=你的（oneapi密码） --spring.datasource.username=你的数据库表名（oneapi）--spring.datasource.url=jdbc:mysql://localhost:3306/oneapi（自己填，如果不是localhost，则删除前面的--net=host）--baseUrlWithoutPath=http(https)://你的one-api的id+端口号

**Comment by Yanyutin753** [comment]
好像搞错了哈哈哈哈哈

**Comment by Yanyutin753** [comment]
复制错了

**Comment by Yanyutin753** [comment]
你看看行不行

**Comment by Yanyutin753** [comment]
我换了一台虚拟机都可以

**Comment by ceozero** [comment]
<img width="726" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/22513657/e03eacb7-2ccd-4783-aef0-0b6e5182d231">
<img width="416" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/22513657/9a3fb3c0-a4ae-4c26-9222-9ceb65acadac">
你好像没明白，，你构建镜像的时候构建一下多平台。。。我只有arm机器。。。amd的镜像跑不动。。。

**Comment by Yanyutin753** [comment]
去学了，不会这个哈哈哈哈哈哈哈

**Comment by ceozero** [comment]
> 去学了，不会这个哈哈哈哈哈哈哈

好吧，等你学会了再push吧。。我先自制镜像用着。

spring.datasource.url 的代码更新上来了吗？

**Comment by Yanyutin753** [comment]
我可以了

**Comment by Yanyutin753** [comment]
你看看，我很奇怪，为啥只有一个
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/132346501/21757544-5c55-4db4-83e0-3e19b95ae2a4)

**Comment by ceozero** [comment]
用 docker manifest push 不同架构镜像，不然后面上传的会顶掉前面的。

**Comment by Yanyutin753** [comment]
我好像成功
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/132346501/2906caaf-b321-446d-8fd9-97385cb1b97b)

**Comment by Yanyutin753** [comment]
是这样吗

**Comment by ceozero** [comment]
> 是这样吗

我拉一下试试。

**Comment by ceozero** [comment]
<img width="1412" alt="image" src="https://github.com/Yanyutin753/fakeApiTool-One-API/assets/22513657/8de6bdcb-8049-4efa-b619-0235763e1060">
可以的，，一切正常。3分钟就玩转docker了。。。牛逼。

**Comment by Yanyutin753** [comment]
gpt太强了只能说，后面把之前的项目也试试打包啊😂

**Comment by ceozero** [comment]
> gpt太强了只能说，后面把之前的项目也试试打包啊😂

看下能不能对接这个，https://github.com/Kerwin1202/chatgpt-web
刚需还能用最新模型。
