### ISSUE TITLE
数据库地址是不是也可以改一下

### ISSUE THREAD

**Issue by mouxangithub** [Yanyutin753/fakeApiTool-One-API#3]
启动服务后发现启动的是本地的数据库地址，而我用的是其他服务器的数据库，所以连不上

**Comment by Yanyutin753** [comment]
可以改，试试改改后端的配置mysql的代码，连接到你的mysql



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Johnathan Abts ***@***.***&gt;
发送时间: 2023年11月17日 10:37
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] 数据库地址是不是也可以改一下 (Issue #3)





 
启动服务后发现启动的是本地的数据库地址，而我用的是其他服务器的数据库，所以连不上

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/132346501/85166676-4500-41d6-b42c-b23aa599dc34)
改这里就好
