### ISSUE TITLE
docker编译的jar在后台添加一个，oneapi出现了三个。

### ISSUE THREAD

**Issue by ceozero** [Yanyutin753/fakeApiTool-One-API#5]
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/22513657/319bdd1d-d00d-40ff-8115-61f87ca0fa2a)
![image](https://github.com/Yanyutin753/fakeApiTool-One-API/assets/22513657/4cc631ad-149b-4e83-a27c-55369efd8508)

只改了application.properties的数据库地址，用mvn构建的jar包。在fake后台添加了一个，，，oneapi就有三个？

另外https://ai.fakeopen.com可以改成官方或者自己的？ 海外机器不需要反代。

**Comment by Yanyutin753** [comment]
这是我弄的，方便轮替，哈哈哈哈哈哈哈也不知道有没有用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ceozero ***@***.***&gt;
发送时间: 2023年11月18日 15:39
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] docker编译的jar在后台添加一个，oneapi出现了三个。 (Issue #5)





 

 
 
只改了application.properties的数据库地址，用mvn构建的jar包。在fake后台添加了一个，，，oneapi就有三个？
 
另外https://ai.fakeopen.com可以改成官方或者自己的？ 海外机器不需要反代。

**Comment by ceozero** [comment]
可能是我没仔细看说明和代码，web的账号密码获取token只是为了自动刷新和方便查看？而不是接入了oneapi让oneapi来使用网页版的token？  给oneapi接入的是潘多拉的免费key和自动刷新？
不知道我这么理解对不对。
我用的是chatgpt-web来架设的，使用的是ChatGPTUnofficialProxyAPI，也就是网页token，然后每隔一段时间就要重新获取，比较麻烦。。以为你这个项目可以自动获取给oneapi用来使用自己的账号。

**Comment by Yanyutin753** [comment]
每次刷新会从账号密码获取token，从而获取key，然后one-api更新渠道，有手动刷新和自动刷新，手动刷新就先点刷新就行，自动刷新每五天进行一次



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ceozero ***@***.***&gt;
发送时间: 2023年11月18日 16:10
收件人: Yanyutin753/fakeApiTool-One-API ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/fakeApiTool-One-API] docker编译的jar在后台添加一个，oneapi出现了三个。 (Issue #5)





 
可能是我没仔细看说明和代码，web的账号密码获取token只是为了自动刷新和方便查看？而不是接入了oneapi让oneapi来使用网页版的token？  给oneapi接入的是潘多拉的免费key和自动刷新？
 不知道我这么理解对不对。
 我用的是chatgpt-web来架设的，使用的是ChatGPTUnofficialProxyAPI，也就是网页token，然后每隔一段时间就要重新获取，比较麻烦。。以为你这个项目可以自动获取给oneapi用来使用自己的账号。

**Comment by ceozero** [comment]
谢谢，，希望大佬弄个自动更新token推送给chatgpt-web。。完美的东西。

**Comment by Yanyutin753** [comment]
我都是用chatgpt next web 你把这个中转站url和令牌放过去，不就可以用了

**Comment by ceozero** [comment]
> 我都是用chatgpt next web 你把这个中转站url和令牌放过去，不就可以用了

潘多拉好像不支持 gpt-3.5-turbo-1106 的模型。试了几次都没成功。
